application: birthday-alerts
version: hand-coded
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "latest"

- name: jinja2
  version: latest
  
handlers:
- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /images
  static_dir: images
  
- url: /.*
  script: app.app
  login: admin
